/**
 * @generacy-ai/credhelper — Session API Contract
 *
 * Types for the credhelper Unix socket control API.
 * Control plane at /run/generacy-credhelper/control.sock
 *
 * POST   /sessions       { role, sessionId }  → { sessionDir, expiresAt }
 * DELETE /sessions/<id>                        → { ok }
 */

// --- Session API ---

export interface BeginSessionRequest {
  /** Role to activate for this session (e.g. "reviewer", "developer") */
  role: string;

  /** Unique session identifier, generated by the worker */
  sessionId: string;
}

export interface BeginSessionResponse {
  /** Path to the session directory under /run/generacy-credhelper/sessions/<id>/ */
  sessionDir: string;

  /** When the session's credentials expire */
  expiresAt: Date;
}

export interface EndSessionRequest {
  /** Session to tear down */
  sessionId: string;
}

// --- LaunchRequest Credentials Field ---

/**
 * Shape consumed by the AgentLauncher credentials interceptor (Phase 3).
 * Added as an optional field on LaunchRequest.
 */
export interface LaunchRequestCredentials {
  /** Which role to request from credhelper */
  role: string;

  /** Workflow uid (e.g. 1001 for generacy-workflow) */
  uid: number;

  /** Workflow gid */
  gid: number;
}
