/**
 * Inline file generators for `generacy init`.
 *
 * Generates CLI-owned files (config.yaml, env template, gitignore,
 * extensions.json) directly from `InitOptions` — no Handlebars needed.
 */
import { stringify } from 'yaml';
import type { InitOptions } from './types.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** VS Code extensions recommended for Generacy projects. */
const GENERACY_EXTENSIONS = ['generacy-ai.agency', 'generacy-ai.generacy'];

/** Comment header prepended to generated config.yaml. */
const CONFIG_HEADER = '# Generated by generacy init — https://generacy.ai\n';

/** Default orchestrator polling interval in milliseconds. */
const DEFAULT_POLL_INTERVAL_MS = 5000;

/** Default worker count for multi-repo orchestrator. */
const DEFAULT_WORKER_COUNT = 3;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert `owner/repo` shorthand to config URL format `github.com/owner/repo`.
 */
function toConfigUrl(shorthand: string): string {
  return `github.com/${shorthand}`;
}

// ---------------------------------------------------------------------------
// Sub-generators
// ---------------------------------------------------------------------------

/**
 * Generate `.generacy/config.yaml` content from init options.
 */
function generateConfigYaml(options: InitOptions): string {
  const config: Record<string, unknown> = {
    schemaVersion: '1',
    project: {
      id: options.projectId,
      name: options.projectName,
    },
    repos: {
      primary: toConfigUrl(options.primaryRepo),
      ...(options.devRepos.length > 0 && {
        dev: options.devRepos.map(toConfigUrl),
      }),
      ...(options.cloneRepos.length > 0 && {
        clone: options.cloneRepos.map(toConfigUrl),
      }),
    },
    defaults: {
      agent: options.agent,
      baseBranch: options.baseBranch,
    },
    ...(options.devRepos.length > 0 && {
      orchestrator: {
        pollIntervalMs: DEFAULT_POLL_INTERVAL_MS,
        workerCount: DEFAULT_WORKER_COUNT,
      },
    }),
    cluster: {
      variant: options.variant,
    },
  };

  return CONFIG_HEADER + stringify(config);
}

/**
 * Generate `.generacy/generacy.env.template` content from init options.
 */
function generateEnvTemplate(options: InitOptions): string {
  let content = `# Generacy environment configuration
# Copy this file to generacy.env and fill in your values.

# --- Project ---
GENERACY_PROJECT_ID=${options.projectId}
GENERACY_BASE_BRANCH=${options.baseBranch}
GENERACY_AGENT=${options.agent}

# --- GitHub ---
GITHUB_TOKEN=<your-github-token>
`;

  if (options.devRepos.length > 0) {
    content += `
# --- Orchestrator (multi-repo) ---
GENERACY_POLL_INTERVAL_MS=${DEFAULT_POLL_INTERVAL_MS}
GENERACY_WORKER_COUNT=${DEFAULT_WORKER_COUNT}
`;
  }

  return content;
}

/**
 * Generate `.generacy/.gitignore` content.
 */
function generateGitignore(): string {
  return `generacy.env
*.log
.cache/
`;
}

/**
 * Generate `.vscode/extensions.json` content, optionally merging with existing.
 *
 * Exported separately so Phase 3 can call it with content from
 * `collectExistingFiles()`.
 *
 * @param existingContent - Existing extensions.json content to merge with.
 * @returns Formatted JSON string with merged recommendations.
 */
export function generateExtensionsJson(existingContent?: string): string {
  let recommendations = new Set<string>(GENERACY_EXTENSIONS);

  if (existingContent) {
    try {
      const existing = JSON.parse(existingContent) as {
        recommendations?: string[];
      };
      if (Array.isArray(existing.recommendations)) {
        for (const ext of existing.recommendations) {
          recommendations.add(ext);
        }
      }
    } catch {
      // Invalid JSON — start fresh with just Generacy extensions
    }
  }

  const result = {
    recommendations: [...recommendations].sort(),
  };

  return JSON.stringify(result, null, 2) + '\n';
}

// ---------------------------------------------------------------------------
// Main generator
// ---------------------------------------------------------------------------

/**
 * Generate all CLI-owned files from init options.
 *
 * Returns a `Map<targetPath, content>` that can be merged with cluster
 * template files and passed to `checkConflicts()` → `writeFiles()`.
 *
 * @param options - Fully resolved init options.
 * @returns Map of relative file paths to generated content.
 */
export function generateCliFiles(options: InitOptions): Map<string, string> {
  const files = new Map<string, string>();

  files.set('.generacy/config.yaml', generateConfigYaml(options));
  files.set('.generacy/generacy.env.template', generateEnvTemplate(options));
  files.set('.generacy/.gitignore', generateGitignore());
  files.set('.vscode/extensions.json', generateExtensionsJson());

  return files;
}
