/**
 * Managed-file disjointness regression test for issue #899.
 *
 * Layer 2 — merge-tree simulation: two sibling branches that each write
 * specs/<feature>/stack.md must merge cleanly, and the merge diff must never
 * mention CLAUDE.md. Proves the disjointness invariant end-to-end.
 *
 * The former Layer 1 (a static grep of the local plan-operation prompt builder)
 * was removed in #1218: cluster workers never execute that wrapper — they run the
 * bare `/plan` slash command installed from agency — so the grep stayed green
 * while the regression it targeted ran free. The invariant now lives in two real
 * enforcement sites:
 *   - prompt-side: pinned in agency (`agency-plugin-spec-kit` tests, agency#511).
 *   - engine-side: `PrManager.commitAndPush` excludes and reverts repo-root
 *     agent-context files from spec-stage commits, covered by
 *     `orchestrator/src/worker/__tests__/pr-manager.agent-context-revert.test.ts`.
 *
 * See specs/899-found-during-cockpit-v1/contracts/merge-tree-invariant.md.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

function git(cwd: string, args: string[]): string {
  return execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  }).trim();
}

describe('managed-file disjointness (issue #899)', () => {
  describe('Layer 2 — merge-tree simulation', () => {
    let repoDir: string;

    beforeAll(() => {
      repoDir = mkdtempSync(join(tmpdir(), 'speckit-managed-'));
    });

    afterAll(() => {
      rmSync(repoDir, { recursive: true, force: true });
    });

    it('two sibling branches writing per-feature stack.md do not conflict on CLAUDE.md', () => {
      git(repoDir, ['init', '-q', '-b', 'main']);
      git(repoDir, ['config', 'user.email', 'test@test']);
      git(repoDir, ['config', 'user.name', 'test']);
      git(repoDir, ['config', 'commit.gpgsign', 'false']);

      writeFileSync(join(repoDir, 'CLAUDE.md'), '# base CLAUDE.md\n');
      git(repoDir, ['add', '-A']);
      git(repoDir, ['commit', '-q', '-m', 'base']);
      const base = git(repoDir, ['rev-parse', 'HEAD']);

      git(repoDir, ['checkout', '-q', '-b', 'feature-a']);
      mkdirSync(join(repoDir, 'specs', 'feature-a'), { recursive: true });
      writeFileSync(
        join(repoDir, 'specs', 'feature-a', 'stack.md'),
        'Generated by /plan — do not hand-edit.\n\nfeature-a stack notes.\n',
      );
      git(repoDir, ['add', '-A']);
      git(repoDir, ['commit', '-q', '-m', 'a']);
      const shaA = git(repoDir, ['rev-parse', 'HEAD']);

      git(repoDir, ['checkout', '-q', 'main']);
      git(repoDir, ['checkout', '-q', '-b', 'feature-b']);
      mkdirSync(join(repoDir, 'specs', 'feature-b'), { recursive: true });
      writeFileSync(
        join(repoDir, 'specs', 'feature-b', 'stack.md'),
        'Generated by /plan — do not hand-edit.\n\nfeature-b stack notes.\n',
      );
      git(repoDir, ['add', '-A']);
      git(repoDir, ['commit', '-q', '-m', 'b']);
      const shaB = git(repoDir, ['rev-parse', 'HEAD']);

      const output = execFileSync(
        'git',
        ['merge-tree', '--write-tree', '-z', '--merge-base', base, shaA, shaB],
        { cwd: repoDir, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] },
      );

      expect(output).not.toMatch(/CONFLICT/);
      expect(output).not.toMatch(/CLAUDE\.md/);
    });
  });
});
