/**
 * Managed-file disjointness regression tests for issue #899.
 *
 * Two layers:
 *   Layer 1 — static-grep drift guard: plan.ts's buildPlanPrompt() must not
 *     mention CLAUDE.md or update_agent. Catches local-shim regressions.
 *   Layer 2 — merge-tree simulation: two sibling branches that each write
 *     specs/<feature>/stack.md must merge cleanly, and the merge diff must
 *     never mention CLAUDE.md. Proves the disjointness invariant.
 *
 * See specs/899-found-during-cockpit-v1/contracts/merge-tree-invariant.md.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const __dirname = dirname(fileURLToPath(import.meta.url));

function git(cwd: string, args: string[]): string {
  return execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  }).trim();
}

describe('managed-file disjointness (issue #899)', () => {
  describe('Layer 2 — merge-tree simulation', () => {
    let repoDir: string;

    beforeAll(() => {
      repoDir = mkdtempSync(join(tmpdir(), 'speckit-managed-'));
    });

    afterAll(() => {
      rmSync(repoDir, { recursive: true, force: true });
    });

    it('two sibling branches writing per-feature stack.md do not conflict on CLAUDE.md', () => {
      git(repoDir, ['init', '-q', '-b', 'main']);
      git(repoDir, ['config', 'user.email', 'test@test']);
      git(repoDir, ['config', 'user.name', 'test']);
      git(repoDir, ['config', 'commit.gpgsign', 'false']);

      writeFileSync(join(repoDir, 'CLAUDE.md'), '# base CLAUDE.md\n');
      git(repoDir, ['add', '-A']);
      git(repoDir, ['commit', '-q', '-m', 'base']);
      const base = git(repoDir, ['rev-parse', 'HEAD']);

      git(repoDir, ['checkout', '-q', '-b', 'feature-a']);
      mkdirSync(join(repoDir, 'specs', 'feature-a'), { recursive: true });
      writeFileSync(
        join(repoDir, 'specs', 'feature-a', 'stack.md'),
        'Generated by /plan — do not hand-edit.\n\nfeature-a stack notes.\n',
      );
      git(repoDir, ['add', '-A']);
      git(repoDir, ['commit', '-q', '-m', 'a']);
      const shaA = git(repoDir, ['rev-parse', 'HEAD']);

      git(repoDir, ['checkout', '-q', 'main']);
      git(repoDir, ['checkout', '-q', '-b', 'feature-b']);
      mkdirSync(join(repoDir, 'specs', 'feature-b'), { recursive: true });
      writeFileSync(
        join(repoDir, 'specs', 'feature-b', 'stack.md'),
        'Generated by /plan — do not hand-edit.\n\nfeature-b stack notes.\n',
      );
      git(repoDir, ['add', '-A']);
      git(repoDir, ['commit', '-q', '-m', 'b']);
      const shaB = git(repoDir, ['rev-parse', 'HEAD']);

      const output = execFileSync(
        'git',
        ['merge-tree', '--write-tree', '-z', '--merge-base', base, shaA, shaB],
        { cwd: repoDir, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] },
      );

      expect(output).not.toMatch(/CONFLICT/);
      expect(output).not.toMatch(/CLAUDE\.md/);
    });
  });

  describe('Layer 1 — static-grep drift guard', () => {
    it('plan.ts prompt does not mention CLAUDE.md or update_agent (drift guard)', async () => {
      const planTs = resolve(__dirname, '..', 'operations', 'plan.ts');
      const source = await readFile(planTs, 'utf8');
      const match = source.match(/function buildPlanPrompt[\s\S]+?^}/m);
      expect(match, 'expected to locate buildPlanPrompt in plan.ts').not.toBeNull();
      const region = match![0];
      expect(region).not.toMatch(/CLAUDE\.md/i);
      expect(region).not.toMatch(/update_agent/i);
    });
  });
});
