import { describe, it, expect } from 'vitest';
import { parse } from 'yaml';
import { generateCliFiles, generateExtensionsJson } from '../file-generators.js';
import type { InitOptions } from '../types.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeOptions(overrides: Partial<InitOptions> = {}): InitOptions {
  return {
    projectId: 'proj-123',
    projectName: 'My Project',
    primaryRepo: 'acme/webapp',
    devRepos: [],
    cloneRepos: [],
    agent: 'claude-code',
    baseBranch: 'main',
    releaseStream: 'stable',
    variant: 'standard',
    force: false,
    dryRun: false,
    skipGithubCheck: false,
    yes: false,
    templateRef: 'main',
    refreshTemplates: false,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// generateCliFiles
// ---------------------------------------------------------------------------

describe('generateCliFiles', () => {
  it('returns all four expected file paths', () => {
    const files = generateCliFiles(makeOptions());

    expect([...files.keys()].sort()).toEqual([
      '.generacy/.gitignore',
      '.generacy/config.yaml',
      '.generacy/generacy.env.template',
      '.vscode/extensions.json',
    ]);
  });

  // -------------------------------------------------------------------------
  // config.yaml
  // -------------------------------------------------------------------------

  describe('config.yaml', () => {
    it('includes the generated-by header', () => {
      const files = generateCliFiles(makeOptions());
      const content = files.get('.generacy/config.yaml')!;

      expect(content).toMatch(/^# Generated by generacy init/);
    });

    it('sets schemaVersion, project id, and name', () => {
      const files = generateCliFiles(makeOptions());
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;

      expect(config.schemaVersion).toBe('1');
      expect(config.project).toEqual({ id: 'proj-123', name: 'My Project' });
    });

    it('converts primary repo shorthand to config URL format', () => {
      const files = generateCliFiles(makeOptions({ primaryRepo: 'acme/webapp' }));
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;

      expect((config.repos as Record<string, unknown>).primary).toBe('github.com/acme/webapp');
    });

    it('sets default agent and base branch', () => {
      const files = generateCliFiles(
        makeOptions({ agent: 'claude-code', baseBranch: 'develop' }),
      );
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;

      expect(config.defaults).toEqual({ agent: 'claude-code', baseBranch: 'develop' });
    });

    it('sets cluster variant', () => {
      const files = generateCliFiles(makeOptions({ variant: 'microservices' }));
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;

      expect(config.cluster).toEqual({ variant: 'microservices' });
    });

    it('omits dev and clone repos when empty', () => {
      const files = generateCliFiles(makeOptions({ devRepos: [], cloneRepos: [] }));
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;
      const repos = config.repos as Record<string, unknown>;

      expect(repos.dev).toBeUndefined();
      expect(repos.clone).toBeUndefined();
    });

    it('includes dev repos when provided', () => {
      const files = generateCliFiles(makeOptions({ devRepos: ['acme/lib-a', 'acme/lib-b'] }));
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;
      const repos = config.repos as Record<string, unknown>;

      expect(repos.dev).toEqual(['github.com/acme/lib-a', 'github.com/acme/lib-b']);
    });

    it('includes clone repos when provided', () => {
      const files = generateCliFiles(makeOptions({ cloneRepos: ['acme/docs'] }));
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;
      const repos = config.repos as Record<string, unknown>;

      expect(repos.clone).toEqual(['github.com/acme/docs']);
    });

    it('adds orchestrator section when dev repos are present', () => {
      const files = generateCliFiles(makeOptions({ devRepos: ['acme/lib-a'] }));
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;

      expect(config.orchestrator).toEqual({
        pollIntervalMs: 5000,
        workerCount: 3,
      });
    });

    it('omits orchestrator section when no dev repos', () => {
      const files = generateCliFiles(makeOptions({ devRepos: [] }));
      const config = parse(files.get('.generacy/config.yaml')!) as Record<string, unknown>;

      expect(config.orchestrator).toBeUndefined();
    });
  });

  // -------------------------------------------------------------------------
  // generacy.env.template
  // -------------------------------------------------------------------------

  describe('generacy.env.template', () => {
    it('contains project id, base branch, and agent', () => {
      const files = generateCliFiles(
        makeOptions({ projectId: 'proj-456', baseBranch: 'develop', agent: 'claude-code' }),
      );
      const env = files.get('.generacy/generacy.env.template')!;

      expect(env).toContain('GENERACY_PROJECT_ID=proj-456');
      expect(env).toContain('GENERACY_BASE_BRANCH=develop');
      expect(env).toContain('GENERACY_AGENT=claude-code');
    });

    it('contains a GITHUB_TOKEN placeholder', () => {
      const files = generateCliFiles(makeOptions());
      const env = files.get('.generacy/generacy.env.template')!;

      expect(env).toContain('GITHUB_TOKEN=<your-github-token>');
    });

    it('includes orchestrator vars when dev repos are present', () => {
      const files = generateCliFiles(makeOptions({ devRepos: ['acme/lib-a'] }));
      const env = files.get('.generacy/generacy.env.template')!;

      expect(env).toContain('GENERACY_POLL_INTERVAL_MS=5000');
      expect(env).toContain('GENERACY_WORKER_COUNT=3');
    });

    it('omits orchestrator vars when no dev repos', () => {
      const files = generateCliFiles(makeOptions({ devRepos: [] }));
      const env = files.get('.generacy/generacy.env.template')!;

      expect(env).not.toContain('GENERACY_POLL_INTERVAL_MS');
      expect(env).not.toContain('GENERACY_WORKER_COUNT');
    });
  });

  // -------------------------------------------------------------------------
  // .gitignore
  // -------------------------------------------------------------------------

  describe('.gitignore', () => {
    it('ignores generacy.env', () => {
      const files = generateCliFiles(makeOptions());
      const gitignore = files.get('.generacy/.gitignore')!;

      expect(gitignore).toContain('generacy.env');
    });

    it('ignores log files and cache directory', () => {
      const files = generateCliFiles(makeOptions());
      const gitignore = files.get('.generacy/.gitignore')!;

      expect(gitignore).toContain('*.log');
      expect(gitignore).toContain('.cache/');
    });
  });

  // -------------------------------------------------------------------------
  // extensions.json (via generateCliFiles)
  // -------------------------------------------------------------------------

  describe('extensions.json', () => {
    it('includes generacy extensions by default', () => {
      const files = generateCliFiles(makeOptions());
      const extensions = JSON.parse(files.get('.vscode/extensions.json')!);

      expect(extensions.recommendations).toContain('generacy-ai.agency');
      expect(extensions.recommendations).toContain('generacy-ai.generacy');
    });

    it('outputs sorted recommendations', () => {
      const files = generateCliFiles(makeOptions());
      const extensions = JSON.parse(files.get('.vscode/extensions.json')!);
      const sorted = [...extensions.recommendations].sort();

      expect(extensions.recommendations).toEqual(sorted);
    });
  });
});

// ---------------------------------------------------------------------------
// generateExtensionsJson (standalone)
// ---------------------------------------------------------------------------

describe('generateExtensionsJson', () => {
  it('returns generacy extensions when no existing content', () => {
    const result = JSON.parse(generateExtensionsJson());

    expect(result.recommendations).toEqual(['generacy-ai.agency', 'generacy-ai.generacy']);
  });

  it('merges with existing recommendations', () => {
    const existing = JSON.stringify({
      recommendations: ['ms-python.python', 'dbaeumer.vscode-eslint'],
    });

    const result = JSON.parse(generateExtensionsJson(existing));

    expect(result.recommendations).toContain('ms-python.python');
    expect(result.recommendations).toContain('dbaeumer.vscode-eslint');
    expect(result.recommendations).toContain('generacy-ai.agency');
    expect(result.recommendations).toContain('generacy-ai.generacy');
  });

  it('deduplicates when existing already includes generacy extensions', () => {
    const existing = JSON.stringify({
      recommendations: ['generacy-ai.agency', 'ms-python.python'],
    });

    const result = JSON.parse(generateExtensionsJson(existing));

    const agencyCount = result.recommendations.filter(
      (r: string) => r === 'generacy-ai.agency',
    ).length;
    expect(agencyCount).toBe(1);
  });

  it('sorts merged recommendations alphabetically', () => {
    const existing = JSON.stringify({
      recommendations: ['z-ext.last', 'a-ext.first'],
    });

    const result = JSON.parse(generateExtensionsJson(existing));
    const sorted = [...result.recommendations].sort();

    expect(result.recommendations).toEqual(sorted);
  });

  it('handles invalid JSON gracefully by using defaults', () => {
    const result = JSON.parse(generateExtensionsJson('not valid json'));

    expect(result.recommendations).toEqual(['generacy-ai.agency', 'generacy-ai.generacy']);
  });

  it('handles JSON without recommendations array', () => {
    const result = JSON.parse(generateExtensionsJson('{"other": true}'));

    expect(result.recommendations).toEqual(['generacy-ai.agency', 'generacy-ai.generacy']);
  });

  it('ends with a trailing newline', () => {
    const raw = generateExtensionsJson();

    expect(raw).toMatch(/\n$/);
  });
});
