export {
  // Schema types
  LogLevelSchema,
  type LogLevel,
  ServerConfigSchema,
  type ServerConfig,
  RedisConfigSchema,
  type RedisConfig,
  GitHubOAuthConfigSchema,
  type GitHubOAuthConfig,
  JWTConfigSchema,
  type JWTConfig,
  AuthConfigSchema,
  type AuthConfig,
  RateLimitConfigSchema,
  type RateLimitConfig,
  CorsConfigSchema,
  type CorsConfig,
  LoggingConfigSchema,
  type LoggingConfig,
  RepositoryConfigSchema,
  type RepositoryConfig,
  MonitorConfigSchema,
  type MonitorConfig,
  DispatchConfigSchema,
  type DispatchConfig,
  OrchestratorConfigSchema,
  type OrchestratorConfig,
  validateConfig,
} from './schema.js';

export { loadConfig, createTestConfig, type LoadConfigOptions } from './loader.js';
